- name: Configure modules load for Kubernetes
  become: true
  shell: |
    echo "overlay" | sudo tee /etc/modules-load.d/k8s.conf
    echo "br_netfilter" | sudo tee -a /etc/modules-load.d/k8s.conf
    sudo modprobe overlay
    sudo modprobe br_netfilter
    echo "net.bridge.bridge-nf-call-iptables = 1" | sudo tee /etc/sysctl.d/k8s.conf
    echo "net.bridge.bridge-nf-call-ip6tables = 1" | sudo tee -a /etc/sysctl.d/k8s.conf
    echo "net.ipv4.ip_forward = 1" | sudo tee -a /etc/sysctl.d/k8s.conf
    sudo sysctl --system
    sudo sysctl -p /etc/sysctl.d/k8s.conf
    sudo sysctl net.bridge.bridge-nf-call-iptables net.bridge.bridge-nf-call-ip6tables net.ipv4.ip_forward



