- name: Configure Kubernetes networking
  hosts: all
  become: true
  tasks:
    - name: Configure modules load for Kubernetes
      lineinfile:
        dest: /etc/modules-load.d/k8s.conf
        line: "{{ item }}"
      with_items:
        - overlay
        - br_netfilter

    - name: Load kernel modules
      shell: |
        sudo modprobe overlay
        sudo modprobe br_netfilter

    - name: Configure sysctl for Kubernetes networking
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: "{{ item }}"
      with_items:
        - "net.bridge.bridge-nf-call-iptables = 1"
        - "net.bridge.bridge-nf-call-ip6tables = 1"
        - "net.ipv4.ip_forward = 1"

    - name: Load kernel modules
      shell: |
        sudo sysctl --system
        sudo modprobe br_netfilter
        sudo sysctl -p /etc/sysctl.conf


