- name: Pull Kubernetes images
  command: kubeadm config images pull
  ignore_errors: yes
  
- name: Create repo directory
  become: true
  file:
    path: /ansible/repo
    state: directory
    mode: '0400'
  

- name: Initialize Kubernetes cluster
  become: true
  shell: "kubeadm init > /ansible/repo/kubeadm-init-output.log"
  register: kubeadm_output
  
- name: Display kubeadm init output
  debug:
    var: kubeadm_output.stdout_lines
    
- name: Save join command to file
  become: true
  copy:
    dest: /ansible/repo/kubeadm-join-command.sh
    content: |
      #!/bin/bash
      kubeadm join {{ master_ip }}:6443 --token {{ kubeadm_output.stdout_lines[-2].split()[-1] }} \
        --discovery-token-ca-cert-hash {{ kubeadm_output.stdout_lines[-1].split()[-1] }}



