- name: Initialize Kubernetes cluster
  hosts: master
  become: true
  tasks:
    - name: Pull Kubernetes images
      command: kubeadm config images pull
      ignore_errors: yes

    - name: Initialize Kubernetes cluster
      command: kubeadm init


