- name: Install containerd
  get_url:
    url: "{{ containerd_tarball_url }}"
    dest: "/tmp/containerd-{{ containerd_version }}-linux-amd64.tar.gz"

- name: Extract containerd
  unarchive:
    src: "/tmp/containerd-{{ containerd_version }}-linux-amd64.tar.gz"
    dest: "/usr/local"
    remote_src: yes

- name: Create systemd directory
  become: true
  file:
    path: /usr/local/lib/systemd/system
    state: directory

- name: Download containerd service file
  get_url:
    url: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"
    dest: "/usr/local/lib/systemd/system/containerd.service"
    
- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start containerd
  systemd:
    name: containerd
    state: started
    enabled: yes



