- name: Download and extract CNI binary
  become: true
  shell: |
    mkdir -p {{ cni_binary_dir_path }}
    cd {{ cni_binary_dir_path }}
    wget {{ cni_binary_url }}
    tar -xzvf cni-plugins-linux-amd64-{{ cni_version }}.tgz
