- name: Install containerd
  get_url:
    url: "{{ containerd_tarball_url }}"
    dest: "/tmp/containerd-{{ containerd_version }}-linux-amd64.tar.gz"

- name: Extract containerd
  unarchive:
    src: "/tmp/containerd-{{ containerd_version }}-linux-amd64.tar.gz"
    dest: "/usr/local"
    remote_src: yes

- name: Copy containerd.service file
  copy:
    src: "containerd.service"
    dest: "{{ containerd_systemd_service_file_path }}"

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start containerd
  systemd:
    name: containerd
    state: started
    enabled: yes



