- name: Download runc binary
  get_url:
    url: "{{ runc_binary_url }}"
    dest: "/tmp/runc"

- name: Install runc binary
  copy:
    src: "/tmp/runc"
    dest: "{{ runc_binary_path }}"
    mode: 'a+x'
