- name: Set executable permission on kubeadm-join-command.sh
  become: true
  file:
    path: /ansible/repo/kubeadm-join-command.sh
    mode: '0755'
- name: Run kubeadm join command on worker node
  become: true
  shell: "/bin/bash /ansible/repo/kubeadm-join-command.sh"


