---
- name: Get join command
  shell: "kubeadm token create --print-join-command --ttl 0"
  register: join_command

- name: Set join command as fact
  set_fact:
    kubernetes_join_command: "{{ join_command.stdout_lines[0] }}"
    when: join_command.stdout_lines is defined

- name: Join node to Kubernetes cluster
  shell: "{{ kubernetes_join_command }}"
  args:
    warn: false
  ignore_errors: true
