---
# This is the main task file that will be executed by Ansible when the role is run
# It will include other task files to perform specific installation and configuration tasks

- include_tasks: install_packages.yml
- include_tasks: install_containerd.yml
- include_tasks: install_runc.yml
- include_tasks: install_cni.yml
- include_tasks: install_crictl.yml
- include_tasks: configure_kernel.yml
- include_tasks: install_kubernetes.yml
- include_tasks: initialize_cluster.yml
  when: inventory_hostname == groups['masters'][0]
- include_tasks: configure_kubectl.yml
  when: inventory_hostname == groups['masters'][0]
- include_tasks: install_weave.yml
  when: inventory_hostname == groups['masters'][0]

